version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.1.1 # using non latest version because of https://github.com/CircleCI-Public/docker-orb/issues/136
  
jobs:
  node-build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build

workflows:
  node-build:
    jobs:
      - node-build
  deploy:
    jobs:
      - run:
          command: echo "export VERSION=$(node -p \"require('./package.json').version\")"
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $VERSION # Gives a tag of the branch name to the docker image
          filters:
            branches:
              only:
                - main
