version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.1.1 # using non latest version because of https://github.com/CircleCI-Public/docker-orb/issues/136
  
jobs:
  node-build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
  docker-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - run: |
          ssh $SSH_USER@$HOST \\<<'ENDSSH'
          ls
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker pull $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          docker stop $CIRCLE_PROJECT_REPONAME
          docker rm $CIRCLE_PROJECT_REPONAME
          docker run --name=$CIRCLE_PROJECT_REPONAME --restart=always --env $DEPLOY_ENV -d $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          ENDSSH

workflows:
  node-build:
    jobs:
      - node-build
  deploy:
    jobs:
      - docker/publish:
          name: docker-publish
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: '$CIRCLE_BRANCH.$CIRCLE_BUILD_NUM,latest'
          filters:
            branches:
              only:
                - main
      - docker-deploy:
          requires:
            - docker-publish
