version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.1.1 # using non latest version because of https://github.com/CircleCI-Public/docker-orb/issues/136

main_only: &main_only
  filters:
    branches:
      only: main

jobs:
  node-build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
  docker-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$HOST \<<'ENDSSH'
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker pull drph4nt0m/game-bot:latest
          docker stop game-bot
          docker rm game-bot
          docker run --name=game-bot --restart=always --env ${DEPLOY_ENV} -d drph4nt0m/game-bot:latest
          ENDSSH

workflows:
  node-build:
    jobs:
      - node-build
  deploy:
    jobs:
      - docker/publish:
          <<: *main_only
          name: docker-publish
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: '$CIRCLE_BRANCH.$CIRCLE_BUILD_NUM,latest'
      - docker-deploy:
          <<: *main_only
          requires:
            - docker-publish
